# Generated by Django 3.2.6 on 2021-08-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
