# Generated by Django 3.2.6 on 2021-08-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210813_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flowerId',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
