# Generated by Django 3.2.6 on 2021-08-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='flowerId',
            field=models.CharField(max_length=100),
        ),
    ]
